### ISSUE TITLE
Stepping Over Ternary Statements Sometimes Hangs Debug Session

### ISSUE THREAD

**Issue by craigsnapgene** [winseros/Qt6Renderer#1]
Running CLion with the Qt6Renderer plugin enabled, I'm sometimes not able to step over a ternary statement. The entire debug session hangs and I'm forced to stop it.

The code sample that follows exhibits this behavior on both Windows 11 and macOS Monterey 12.5.1. Other platforms weren't tested. Note that it's hit-or-miss whether the debugger hangs. On macOS, sometimes there will be a 30 second hang, but other times you could wait several minutes and give up.

CLion 2022.2.3
Build #CL-222.4167.35, built on September 15, 2022
Non-Bundled Plugins:
    IdeaVIM (1.11.1)
    n.v.k.Qt6Renderer (1.0.0)

```cpp
int main( int argc, char **argv )
{
  struct A
  {
    QString getString() const
    { return "Hello"; }

    QString getAnotherString() const
    { return someFunc(); }

  private:
    QString someFunc() const
    { return "some message"; }
  };

  struct B : public A
  {};

  constexpr bool someCondition = false;
  B* b = new B;

  auto stepOverMe = ( someCondition ?
                      b->getString() :
                      b->getAnotherString() );

  return 0;
}
```

**Comment by winseros** [comment]
Hi, I know about such problem. It occurs a random way on different environments and different code samples. The sample you provided works fine on all of my environments, but I have a bunch of samples that cause this behavior.

Still could not find the source of issue.

**Comment by winseros** [comment]
Hi. As v`1.1.0` has been released, I anticipate that the problem will be fixed there. Most of the LLDB code was redone.
