### ISSUE TITLE
Clarify the needness of manual installation step

### ISSUE THREAD

**Issue by Ashark** [winseros/Qt6Renderer#14]
Currently, readme contains the section called "Manual Installation". It is describing downloading the project (or qt6renderer just folder) and the .gdbinit setup.

But it is not clear if this setup is needed in case you use IDE with the renderer extension. The user may expect that in case you install Qt6Renderer plugin (in CLion or in VS Code), they do not need to do any manual setup further.

Can this be explained in readme?

**Comment by winseros** [comment]
If an IDE plugin is used, this step is not required. This step is for people who:
- Either uses an IDE, for which there is no plugin. 
- Or runs GDB directly without an IDE.

I'll update the README with the relevant notice. 

Thank you!

**Comment by winseros** [comment]
I added the notice 6c438fce2cb5685de7be88066001f4cbd8503fd1
