### ISSUE TITLE
no data visible

### ISSUE THREAD

**Issue by reybeamde** [winseros/Qt6Renderer#7]
I installed the plugin on Linux (Kubuntu 23.10) with clion CLion 2023.3.4, bundled gdb 13.2, Qt 6.4.2, and tested with the example program given in your repository. But no data is visible. Are there any further settings or dependencies?

![image](https://github.com/winseros/Qt6Renderer/assets/81241371/eab6f2d5-8cb8-4fd0-8310-27a8513911a2)

**Comment by winseros** [comment]
Hi, which Qt version did you use?

**Comment by winseros** [comment]
Please try a different version of Qt. 

There are problematic Qt versions, for which the debugger is unable to extract type metadata. I am aware of `6.2.4` and `6.4.2`, but there may be further ones as well.

You can use the `GDB` console to make a quick check if a specific version includes type metainfo by setting a breakpoint and running the command:

```
python print(gdb.parse_and_eval('*(&qtHookData)'))
```

For examlpe, "good" `6.6.1` gives the output:
![image](https://github.com/winseros/Qt6Renderer/assets/6763540/0143c11e-6e7f-42dc-ac60-891fadd438e8)

And the `6.4.2` gives:
![image](https://github.com/winseros/Qt6Renderer/assets/6763540/9088cd37-cc92-462b-aed2-36025dcb9c65)

**Comment by reybeamde** [comment]
With 6.6.1 i get the same result
![image](https://github.com/winseros/Qt6Renderer/assets/81241371/f4072405-85a9-47ba-8112-f699d3c386aa)

**Comment by winseros** [comment]
Do you have `Debug information files` installed?
![image](https://github.com/winseros/Qt6Renderer/assets/6763540/f4317afc-09bb-4911-9de3-4616095fc09b)

**Comment by reybeamde** [comment]
yes sorry, i forgot to download the debug info files for 6.6.1. 

It's working now. Thanks a lot for your help and the great plugin :)
